- test/jdk/java/lang/System/SecurityManagerWarnings.java
Related: https://github.com/eclipse-openj9/openj9/pull/20625
port from: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/905
> Update SecurityManagerWarnings to match OpenJ9 stack trace

- src/java.base/share/classes/jdk/internal/loader/URLClassPath.java
URLClassPath.getResource(String name, boolean check) was removed in 24
due to the security manager removal. The OpenJ9 patch to updated the
scc's search path was lost because of this change.
Copied from Java 23: https://github.com/ibmruntimes/openj9-openjdk-jdk23/blob/openj9/src/java.base/share/classes/jdk/internal/loader/URLClassPath.java#L420-L422
Related to https://github.com/eclipse-openj9/openj9/issues/20702
Port to next: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/914
> Add missing update to the shared class cache search path

- src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
Reverting a previous commit (8ddd8d766221c1ac26455512698bcf58d6e24a1c) that added support for EC aliases in KeyFactory and KeyPairGenerator for SunPKCS11.
This was previously supported in Java 8 on Z by the IBMPKCS11Impl provider. However, an openjdk contributer noted that OID is not commonly used for the KeyFactory and KeyGenerator services. Instead, the standard "EC" string should be used as an input to generate EC keys.
Given the upstream stance, no requests for continuing this support, and the availability of an alternative, this change should be removed.
> Remove support for EC aliases in SunPKCS11

- closed/src/java.base/share/classes/java/io/ClassByNameCache.java
- closed/src/java.base/share/classes/jdk/crypto/jniprovider/NativeCrypto.java
- closed/src/java.base/share/classes/openj9/internal/security/RestrictedSecurity.java
Related to https://github.com/eclipse-openj9/openj9/issues/20563
Port from https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/932
> Remove AccessController.doPrivileged uses from closed/src

- closed/DDR.gmk
- closed/GensrcJ9JCL.gmk
- closed/custom/Main.gmk
Create a second copy suitable for use with the boot JDK.
Delay DDR compile_check to use the exploded JDK.
This is a back-port of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/933.
> Allow use of conditional code in DDR tools

- closed/GensrcJ9JCL.gmk
- src/java.base/share/classes/jdk/internal/ref/CleanerImpl.java
CRIU adds `@NotCheckpointSafe` for `CleanerImpl.CleanableList.insert()`
Removed `jdk/internal/ref/PhantomCleanable.java` from `COPY_OVERLAY_FILES` list which only applies to JDK21 and earlier versions due to the change of `CleanerImpl.CleanableList` since JDK24.
Cherry-pick
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/936
closes https://github.com/eclipse-openj9/openj9/issues/21111
> CRIU adds @NotCheckpointSafe for CleanerImpl.CleanableList.insert()

- test/hotspot/jtreg/serviceability/jvmti/events/MonitorWaited/monitorwaited01/libmonitorwaited01.cpp
- test/hotspot/jtreg/serviceability/jvmti/vthread/VThreadEventTest/libVThreadEventTest.cpp
OpenJ9 has its own implementation of virtual threads in the JVM.
Due to differences in implementation, the `monitorwaited01` and
`VThreadEventTest` tests have been updated to check the function names
used in OpenJ9's virtual thread implementation.
Related: https://github.com/eclipse-openj9/openj9/issues/19191
Related: https://github.com/eclipse-openj9/openj9/issues/20707
Backport of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/938
> Update monitorwaited01 and VThreadEventTest to work with OpenJ9

- closed/DDR.gmk
- closed/OpenJ9.gmk
- closed/autoconf/custom-spec.gmk.in
- closed/make/modules/openjceplus/Lib.gmk
- closed/openssl.gmk
Export `INCLUDE` only where it is needed.
Use `MixedPath` in `DDR.gmk` to get usable paths on Windows.
This is a back-port of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/943.
> Update makefiles for Windows

- closed/GensrcJ9JCL.gmk
- src/java.base/share/classes/jdk/internal/ref/CleanerImpl.java
- src/java.base/share/classes/jdk/internal/ref/PhantomCleanable.java
CRIU adds `@NotCheckpointSafe` for `PhantomCleanable` constructor
`@NotCheckpointSafe` should be added for the caller of the `synchronized` method `list.insert(this)`, i.e., `PhantomCleanable(T referent, Cleaner cleaner)`.
Cherry-pick
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/944
closes https://github.com/eclipse-openj9/openj9/issues/21111
> CRIU adds @NotCheckpointSafe for PhantomCleanable constructor

- closed/custom/common/Modules.gmk
This is a back-port of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/953.
> Add openj9.cuda and openj9.dtfj to NATIVE_ACCESS_MODULES

- closed/custom/common/Modules.gmk
The openjceplus module makes use of native code which results in a warning message being printed on Java 24 and higher. This update adds the openjceplus module to the NATIVE_ACCESS_MODULES which suppresses this warning message.
Back-ported from: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/955
Signed-off-by: Jason Katonica <katonica@us.ibm.com>
> Add openjceplus module to NATIVE_ACCESS_MODULES

- closed/src/java.base/share/classes/openj9/internal/security/RestrictedSecurity.java
Fix `selectedProfile` overridden by a `null` property `semeru.customprofile`
Cherry-pick
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/956
> Fix selectedProfile overridden by a null property semeru.customprofile

- closed/GensrcJ9JCL.gmk
- src/java.base/share/classes/jdk/internal/ref/CleanerImpl.java
- src/java.base/share/classes/jdk/internal/ref/PhantomCleanable.java
CRIU adds `@NotCheckpointSafe` for `CleanerImpl.CleanableList` methods
Added `@NotCheckpointSafe` to `CleanerImpl.CleanableList` `isEmpty()`, `insert()` and `remove()`.
Cherry-pick
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/960
> CRIU adds @NotCheckpointSafe for CleanerImpl.CleanableList methods

- test/jdk/sun/security/tools/jarsigner/TimestampCheck.java
8352302: Test sun/security/tools/jarsigner/TimestampCheck.java is failing
https://github.com/openjdk/jdk24u/commit/9880a973ea1538eb9bee061cdf53ea75397364e9
Issue https://github.com/eclipse-openj9/openj9/issues/21436
The head stream will get this naturally via https://github.com/openjdk/jdk/commit/577ede73d8e916bac9050d3bee80d2f18cc833a7.
jdk24 should also get it naturally, likely for 24.0.1, but bring it in now to avoid the failure.
> Integrate fix for 8352302

- test/jdk/ProblemList-OpenJCEPlus.txt
Add ProblemList-OpenJCEPlus.txt as placeholder
related: https://github.com/adoptium/aqa-tests/pull/6129, https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/977#issuecomment-2770313607 and automation/issues/78
> Add ProblemList-OpenJCEPlus.txt as placeholder for JDK24

- test/hotspot/jtreg/serviceability/jvmti/vthread/StopThreadTest/StopThreadTest.java
OpenJ9 only supports a single implementation; so, the code related to the legacy locking mode has been removed.
OpenJ9 does not support the below options:
```
-XX:+UnlockExperimentalVMOptions -XX:-VMContinuations
```
The test mode that uses the above options has been removed.
Related: https://github.com/eclipse-openj9/openj9/issues/21413.
Backport of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/979.
> Modify StopThreadTest to work with OpenJ9's JEP491 implementation

- make/conf/version-numbers.conf
This reverts commit 7eecd87f883765a779e8221e998ec25a4183605c.
https://github.com/eclipse-openj9/openj9/pull/21627 needs to be merged first.
> Revert "Allow JDK 21 for boot jdk"

- test/hotspot/jtreg/serviceability/jvmti/events/MonitorWaited/monitorwaited01/libmonitorwaited01.cpp
Related: https://github.com/eclipse-openj9/openj9/issues/21402, https://github.com/eclipse-openj9/openj9/pull/21590
> Update monitorwaited test to match OpenJ9 impl

- test/jdk/java/lang/Thread/virtual/SynchronizedNative.java
Increase time out for `java/lang/Thread/virtual/SynchronizedNative.java`
Related to 
* https://github.com/eclipse-openj9/openj9/issues/21727
Cherry-pick
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/1001
> Increase time out for java/lang/Thread/virtual/SynchronizedNative.java

- test/hotspot/jtreg/serviceability/jvmti/vthread/StopThreadTest/StopThreadTest.java
- test/jdk/java/lang/Thread/virtual/LockingMode.java
- test/jdk/java/lang/Thread/virtual/MonitorEnterExit.java
Use `VM.isYieldBlockedVirtualThreadsEnabled()` check the legacy lock mode
The legacy locking mode is enabled if `com.ibm.oti.vm.VM.isYieldBlockedVirtualThreadsEnabled()` returns `false`.
Cherry-pick
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/1013
The PR build doesn't validate the test change.
Verified via [a personal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50383/console)
> Use VM.isYieldBlockedVirtualThreadsEnabled() check the legacy lock mode

- test/jdk/java/lang/Thread/virtual/MonitorWaitNotify.java
- test/jdk/java/lang/Thread/virtual/Parking.java
- test/jdk/java/lang/Thread/virtual/ThreadAPI.java
Fix error: package `com.ibm.oti.vm` is not visible
Cherry-pick
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/1014
This resolves the test compilation error - https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/80/consoleFull
```
21:54:31  /home/jenkins/workspace/Test_openjdk24_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Thread/virtual/LockingMode.java:40: error: package com.ibm.oti.vm is not visible
21:54:31          return !com.ibm.oti.vm.VM.isYieldBlockedVirtualThreadsEnabled();
21:54:31                             ^
21:54:31    (package com.ibm.oti.vm is declared in module java.base, which does not export it to the unnamed module)
```
Verified at [a grinder w/ …
> Fix error: package com.ibm.oti.vm is not visible
